const config = {
  dev: {
    HOSTNAME: "https://localhost",
    PORT: "3004",
    NODE_TLS_REJECT_UNAUTHORIZED: 0,
    TARGET_HOST_HOSTNAME: "https://10.138.39.236",
    TARGET_HOST_PORT: "9000",
    SAML_CALLBACK_LOGIN_PATH: "/api/v1/login/callback",
    SAML_CALLBACK_LOGOUT_PATH: "/api/v1/logout/callback",
    SMAL_ENTRY_POINT: "https://test-ids.ais.co.th/samlsso",
    SAML_ISUER: "TTSTRANSFORM",
    LOG_HOSTNAME: "TTSNETA802C",
    LOG_APPNAME: "TTS-TRANSFORM-NODE",
    LOG_CHANNEL: "TTS-TRANSFORM-NODE",
    PROJECT_CODE: "TTS",
    LOG_PATH: "./logs",
    LOG_ROTATE_TIME: "15",
    MULTIPLE_LOGIN: false,
    LOGIN_BY_PASS: true,
    SERVER_PRIVATE_KEY_PATH: "./server.key",
    SERVER_CERTIFICATE_PATH: "./server.crt",
  },
  test: {
    HOSTNAME: "https://10.137.21.212",
    PORT: "3004",
    NODE_TLS_REJECT_UNAUTHORIZED: 0,
    TARGET_HOST_HOSTNAME: "http://10.138.39.220",
    TARGET_HOST_PORT: "9000",
    SAML_CALLBACK_LOGIN_HOSTNAME_PATH:
      "https://devtts-asc.intra.ais/login-callback",
    SAML_CALLBACK_LOGIN_PATH: "/login-callback",
    SAML_CALLBACK_LOGOUT_PATH: "/logout-callback",
    SMAL_ENTRY_POINT: "https://test-ids.ais.co.th/samlsso",
    SAML_ISUER: "TTSASC",
    LOG_HOSTNAME: "ASCNETA802C",
    LOG_APPNAME: "TTS-ASC-NODE",
    LOG_CHANNEL: "TTS-ASC-NODE",
    PROJECT_CODE: "ASC",
    LOG_PATH: "./logs",
    LOG_ROTATE_TIME: "15",
    MULTIPLE_LOGIN: true,
    LOGIN_BY_PASS: true,
    SERVER_PRIVATE_KEY_PATH: "./app/keystore/server.key",
    SERVER_CERTIFICATE_PATH: "./app/keystore/server.crt",
  },
  test2: {
    HOSTNAME: "https://localhost",
    PORT: "3004",
    SOCKET_PORT: "3005",
    NODE_TLS_REJECT_UNAUTHORIZED: 0,
    TARGET_HOST_HOSTNAME: "https://10.138.39.220",
    TARGET_HOST_PORT: "9000",
    SAML_CALLBACK_LOGIN_PATH: "/login-callback",
    SAML_CALLBACK_LOGOUT_PATH: "/logout-callback",
    SMAL_ENTRY_POINT: "https://test-ids.ais.co.th/samlsso",
    SAML_ISUER: "TTSASC",
    LOG_HOSTNAME: "ASCNETA802C",
    LOG_APPNAME: "TTS-ASC-NODE",
    LOG_CHANNEL: "TTS-ASC-NODE",
    PROJECT_CODE: "ASC",
    LOG_PATH: "./logs",
    LOG_ROTATE_TIME: "15",
    MULTIPLE_LOGIN: true,
    LOGIN_BY_PASS: true,
    SERVER_PRIVATE_KEY_PATH: "./cert/server.key",
    SERVER_CERTIFICATE_PATH: "./cert/server.crt",
    HTTP_HEADER_SERVER: "Advance Info Service Co.,Ltd.",
    HTTP_HEADER_ACCESS_CONTROL_ALLOW_ORIGIN: "*",
    HTTP_HEADER_ACCESS_CONTROL_ALLOW_CREDENTIALS: "true",
    HTTP_HEADER_ACCESS_CONTROL_ALLOW_HEADERS:
      "Origin, X-Requested-With, IP-Address,Content-Type, Accept, Authorization",
    HTTP_HEADER_ACCESS_CONTROL_ALLOW_METHODS: "GET,POST",
    HTTP_HEADER_ACCESS_CONTROL_EXPOSE_HEADERS: "Content-Disposition",
    HTTP_HEADER_X_FRAME_OPTIONS: "SAMEORIGIN",
    HTTP_HEADER_X_POWERED_BY: "N/A",
    HTTP_HEADER_X_XSS_PROTECTION: "1; mode=block",
    HTTP_HEADER_CACHE_CONTROL: "private",
    HTTP_HEADER_CONTENT_TYPE: "text/html; charset=utf-8",
    HTTP_HEADER_X_CONTENT_TYPE_OPTIONS: "nosniff",
    HTTP_HEADER_STRICT_TRANSPORT_SECURITY:
      "max-age=31536000;includeSubdomains;preload;",
    HTTP_HEADER_CONTENT_SECURITY_POLICY:
      "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:; script-src * 'unsafe-inline' 'unsafe-eval' data: blob:; connect-src * 'unsafe-inline'; img-src * data: blob: 'unsafe-inline'; frame-src *; style-src * 'unsafe-inline'; font-src 'self' * data:;",
  },
  test3: {
    HOSTNAME: "https://localhost",
    PORT: "3004",
    SOCKET_PORT: "3005",
    NODE_TLS_REJECT_UNAUTHORIZED: 0,
    TARGET_HOST_HOSTNAME: "https://localhost",
    TARGET_HOST_PORT: "9000",
    SAML_CALLBACK_LOGIN_PATH: "/login-callback",
    SAML_CALLBACK_LOGOUT_PATH: "/logout-callback",
    SMAL_ENTRY_POINT: "https://test-ids.ais.co.th/samlsso",
    SAML_ISUER: "TTSASC",
    LOG_HOSTNAME: "ASCNETA802C",
    LOG_APPNAME: "TTS-ASC-NODE",
    LOG_CHANNEL: "TTS-ASC-NODE",
    PROJECT_CODE: "ASC",
    LOG_PATH: "./logs",
    LOG_ROTATE_TIME: "15",
    MULTIPLE_LOGIN: true,
    LOGIN_BY_PASS: true,
    SERVER_PRIVATE_KEY_PATH: "./cert/server.key",
    SERVER_CERTIFICATE_PATH: "./cert/server.crt",
    HTTP_HEADER_SERVER: "Advance Info Service Co.,Ltd.",
    HTTP_HEADER_ACCESS_CONTROL_ALLOW_ORIGIN: "*",
    HTTP_HEADER_ACCESS_CONTROL_ALLOW_CREDENTIALS: "true",
    HTTP_HEADER_ACCESS_CONTROL_ALLOW_HEADERS:
      "Origin, X-Requested-With, IP-Address,Content-Type, Accept, Authorization",
    HTTP_HEADER_ACCESS_CONTROL_ALLOW_METHODS: "GET,POST",
    HTTP_HEADER_ACCESS_CONTROL_EXPOSE_HEADERS: "Content-Disposition",
    HTTP_HEADER_X_FRAME_OPTIONS: "SAMEORIGIN",
    HTTP_HEADER_X_POWERED_BY: "N/A",
    HTTP_HEADER_X_XSS_PROTECTION: "1; mode=block",
    HTTP_HEADER_CACHE_CONTROL: "private",
    HTTP_HEADER_CONTENT_TYPE: "text/html; charset=utf-8",
    HTTP_HEADER_X_CONTENT_TYPE_OPTIONS: "nosniff",
    HTTP_HEADER_STRICT_TRANSPORT_SECURITY:
      "max-age=31536000;includeSubdomains;preload;",
    HTTP_HEADER_CONTENT_SECURITY_POLICY:
      "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:; script-src * 'unsafe-inline' 'unsafe-eval' data: blob:; connect-src * 'unsafe-inline'; img-src * data: blob: 'unsafe-inline'; frame-src *; style-src * 'unsafe-inline'; font-src 'self' * data:;",
  },
  sit: {
    HOSTNAME: "https://10.137.21.212",
    PORT: "3000",
    NODE_TLS_REJECT_UNAUTHORIZED: 0,
    TARGET_HOST_HOSTNAME: "https://10.138.39.220",
    TARGET_HOST_PORT: "9000",
    SAML_CALLBACK_LOGIN_PATH: "/api/v1/login/callback",
    SAML_CALLBACK_LOGOUT_PATH: "/api/v1/logout/callback",
    SMAL_ENTRY_POINT: "https://test-ids.ais.co.th/samlsso",
    SAML_ISUER: "TTSTRANSFORM",
    LOG_HOSTNAME: "TTSNETA802C",
    LOG_APPNAME: "TTS-TRANSFORM-NODE",
    LOG_CHANNEL: "TTS-TRANSFORM-NODE",
    PROJECT_CODE: "TTS",
    LOG_PATH: "./logs",
    LOG_ROTATE_TIME: "15",
    MULTIPLE_LOGIN: false,
    LOGIN_BY_PASS: false,
    SERVER_PRIVATE_KEY_PATH: "./server.key",
    SERVER_CERTIFICATE_PATH: "./server.crt",
  },
  prod: {
    HOSTNAME: "https://tts-asc.intra.ais",
    PORT: "3004",
    SOCKET_PORT: "3005",
    NODE_TLS_REJECT_UNAUTHORIZED: 0,
    TARGET_HOST_HOSTNAME: "https://tts-asc-app.intra.ais",
    TARGET_HOST_PORT: "443",
    SAML_CALLBACK_LOGIN_PATH: "/login-callback",
    SAML_CALLBACK_LOGOUT_PATH: "/logout-callback",
    SMAL_ENTRY_POINT: "https://ids.ais.co.th/samlsso",
    SAML_ISUER: "TTSASC",
    LOG_HOSTNAME: "ASCNETA802C",
    LOG_APPNAME: "TTS-ASC-NODE",
    LOG_CHANNEL: "TTS-ASC-NODE",
    PROJECT_CODE: "ASC",
    LOG_PATH: "./logs",
    LOG_ROTATE_TIME: "15",
    MULTIPLE_LOGIN: true,
    LOGIN_BY_PASS: true,
    SERVER_PRIVATE_KEY_PATH: "./server.key",
    SERVER_CERTIFICATE_PATH: "./server.crt",
  },
  abc: {
    HOSTNAME: "http://127.0.0.1",
    PORT: "3000",
    NODE_TLS_REJECT_UNAUTHORIZED: 0,
    TARGET_HOST_HOSTNAME: "https://10.138.39.236",
    TARGET_HOST_PORT: "9000",
    SAML_CALLBACK_PATH: "/api/v1/login/callback",
    SMAL_ENTRY_POINT: "https://test-ids.ais.co.th/samlsso",
    SAML_ISUER: "TTS_TRANSFORM",
    LOG_HOSTNAME: "TTSNETA802C",
    LOG_APPNAME: "TTS-TRANSFORM-NODE",
    LOG_CHANNEL: "TTS-TRANSFORM-NODE",
    PROJECT_CODE: "TTS",
    LOG_PATH: "./logs",
    LOG_ROTATE_TIME: "15",
    MULTIPLE_LOGIN: false,
    LOGIN_BY_PASS: false,
    SERVER_PRIVATE_KEY_PATH: "./server.key",
    SERVER_CERTIFICATE_PATH: "./server.crt",
  },
};

module.exports = config;
